### ISSUE TITLE
TYMA_TIKL_ALL_AT_ONCE handling must be included

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BlueZone-Scripts-Installer#19]

**Comment by theVKC** [comment]
@CDPotter, I presume you'll want to include this one. Also, see that we're doing it in HTML/JavaScript now? You won't need Visual Studio anymore.

**Comment by CDPotter** [comment]
Well my vested interest in this has changed quite a bit lately but I can give it a shot.

**Comment by theVKC** [comment]
#33 now handles this. I'll close this issue.
